# Generated by Django 5.0.6 on 2024-07-24 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='age',
            new_name='district',
        ),
        migrations.AddField(
            model_name='guest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
