# Generated by Django 5.0.6 on 2024-07-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_message_topic_delete_guest_room_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=100)),
                ('sclass', models.IntegerField()),
                ('saddress', models.CharField(max_length=100)),
            ],
        ),
    ]
