# Generated by Django 5.0.6 on 2024-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('customer', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
