# Generated by Django 5.0.6 on 2024-08-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_shop_alter_school_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.CharField(max_length=100)),
                ('teachers', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
