# Generated by Django 5.0.6 on 2024-08-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tables', models.IntegerField()),
                ('associates', models.CharField(max_length=100)),
            ],
        ),
    ]
