# Generated by Django 5.0.6 on 2024-08-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_office'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='office',
            new_name='hotel',
        ),
    ]
