# Generated by Django 5.0.6 on 2024-08-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_office_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
